server:
    port: 8080

spring:
    application:
      name: KartoshkaWallet
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: jdbc:postgresql://${HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: ${DDL_AUTO}
    flyway:
        enabled: true
        locations:
          - db.migration
        url: jdbc:postgresql://${HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        user: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}
    main:
        allow-bean-definition-overriding: true

jwt:
    secret: ${JWT_SECRET}
    access: ${JWT_ACCESS}
    refresh: ${JWT_REFRESH}


management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
    endpoint:
        health:
            show-details: ALWAYS
        prometheus:
            enabled: true
    prometheus:
        metrics:
            export:
                enabled: true
    metrics:
        distribution:
            percentiles-histogram:
                "[http.server.requests]": true
        enable:
          jvm: true
