apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    inputName: DS_PROMETHEUS
    url: http://prometheus:9090
    isDefault: true
    basicAuth: false
    editable: true